name: Migrate SQLite to Supabase

on:
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    inputs:
      sqlite_path:
        description: 'Path to the sqlite DB file in the workspace (relative or absolute)'
        required: false
        default: '../disclosr_backend/disclosr.db'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scripts/migrate_to_supabase.py --sqlite "${{ github.event.inputs.sqlite_path || '../disclosr_backend/disclosr.db' }}" --pg "${{ secrets.DATABASE_URL }}"
